service: chatbot-backend
frameworkVersion: '3.33.0'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: send
          method: post
      - http:
          path: report
          method: post
      - http:
          path: test
          method: get