# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["development"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present
      - name: Create .env file
        run: |
          #!/bin/bash

          # Assign the values to variables
          api_key="${{ secrets.API_KEY }}"
          port="${{ secrets.PORT }}"
          Authorization="${{ secrets.Authorization }}"

          # Create the .env file
          cat <<EOF >.env
          API_KEY=${api_key}
          PORT=${port}
          Authorization=${Authorization}
          EOF

          echo ".env file created successfully."
      - run: sudo pm2 restart chatserver
